version: '3.9'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - BASE_URL=http://app:5000
      - BOT_URL=http://bot:8000
      - SECRET_KEY=sup3r_s3cr3t_k3y
    depends_on:
      - bot

  bot:
    build: ./bot
    environment:
      - FLAG=xss{gu3ssing_th3_n0nc3_w4as_pr3tty_e4sy_r1ght?}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 2s
      retries: 5
